### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by onweer** [sail-sail/ejsExcel#10]
![image](https://user-images.githubusercontent.com/11755669/27366132-ba580aa0-5676-11e7-8e5c-87d3eb1bd5b1.png)

**Comment by sail-sail** [comment]
nodejs 版本 操作系统64位还是32位
内部有一个模块是需要编译的 node-expat 模块

**Comment by sail-sail** [comment]
你可以手动编译node-expat模块, 大多数版本, 我已经编译好了
ejsExcel\lib\node-expat\lib 路径下面 类似 expat.node_v51_win32_x64

**Comment by onweer** [comment]
@sail-sail nodejs  v8.1.1  npm : v5.0.3， 操作系统是 MacOSX 10.12.4

**Comment by onweer** [comment]
@sail-sail 只能在 window 环境使用吗？

**Comment by sail-sail** [comment]
nodejs v8.1.1 的 node-expat 还没有编译, 你可以用xcode编译一下,
用xcode编译 node-expat 模块后改名为 expat.node_v57_darwin_x64 放在 lib\node-expat\lib 路径下

**Comment by sail-sail** [comment]
编译好之后, 可以发一份给我,

**Comment by sail-sail** [comment]
@onweer 之前的版本, 安装有些模块需要编译,我就帮忙提前编译所有的平台, 但是难免有遗漏, 比如Mac系统
从现在开始, 3.4.0 版本开始, 我用纯js代码重写了之前需要编译的部分,  现在 3.4.0 可以直接使用, 无需再变异了
