### ISSUE TITLE
升级后列数运算有问题

### ISSUE THREAD

**Issue by panio123** [sail-sail/ejsExcel#11]
升级最新版后，发现无法进行 列数 运算了，结果总是为nan。

``` html
<%=_row - 1%>
--
<%=_col - 1%>

```
``` html
11
--
NaN
```

另外，灰常感谢作者的大作，用起来很爽。

**Comment by panio123** [comment]
不好意思，好像一直都是不支持列运算的，因为列是字母，打扰了。

**Comment by panio123** [comment]
额，非常不好意思。
顺便贴一下列运算的思路，目前我的列运算不会超过Z，所以可以用以下方法进行运算：

```js
String.fromCharCode(_col.charCodeAt() - 1)
```

如果超过Z了，那得封闭个方法了，希望作者能实现这个方法哦，谢谢啦。

**Comment by sail-sail** [comment]
你应该用 <%=_charPlus_(_col,3)%> 这个方法进行列运算

**Comment by sail-sail** [comment]
你应该用 <%=_charPlus_(_col,3)%> 这个方法进行列运算

**Comment by sail-sail** [comment]
<%=_charPlus_(_col,3)%> 文档test/test.xlsx 里面有说明, 这个方法进行列运算

**Comment by panio123** [comment]
哦哦，那好的，非常感谢。
