### ISSUE TITLE
chart

### ISSUE THREAD

**Issue by IhorLaputin** [sail-sail/ejsExcel#12]
How to set dynamic  range for Chart ? like =SUM('H2;H'+(_row-1))

**Comment by sail-node** [comment]
<%#"=SUM('H2;H'"+(_row-1)+")"%>

The  #  means output formula.

You can set the test/test.xlsx. And run test.bat.

**Comment by sail-sail** [comment]
<%#"=SUM('H2;H'"+(_row-1)+")"%>

The # means output formula.

You can set the test/test.xlsx. And run test.bat.
