### ISSUE TITLE
是否可以考虑能够在_data_中设置图片的buffer

### ISSUE THREAD

**Issue by judgeou** [sail-sail/ejsExcel#13]
是否可以考虑能够在_data_中设置图片的buffer

就是像这样的用法
`<%_img_({imgBuffer:_data_.imgBuffer,cellNumAdd:2,rowNumAdd:2})%>`

**Comment by sail-sail** [comment]
经再次测试, 实早已支持!

**Comment by judgeou** [comment]
用法就像是我这样？能否提供例子？

**Comment by sail-sail** [comment]
对啊, 这是javascript本身的语法啊, 我不知道是不是这样用, 得看你的变量是不是一个图片的buffer对象
只要是图片的buffer对象, 传进去, 就可以
