### ISSUE TITLE
Excel Template格式

### ISSUE THREAD

**Issue by michellechsy** [sail-sail/ejsExcel#14]
template里边支持的格式都有哪些啊？ 参照test里边那些模版在renderExcel的时候一直报错（如下），过不去啊
error:  SyntaxError: Invalid or unexpected token

**Comment by sail-sail** [comment]
支持任意格式!! 你可以单独测试test.xlsx 没问题就你写错了
你看看你js的语法,应该错了

**Comment by sail-sail** [comment]
不行就加Q群, 发你的模板过来, 我帮你看看你的javascript的语法是哪里不对吧

**Comment by sail-sail** [comment]
我看了下, test/test.xlsx 文档里面也有说,支持Excel模板的任意格式

**Comment by michellechsy** [comment]
嗯，测出来了，template里边的语法写错了。 :)
