### ISSUE TITLE
模版里配置了table的样式，生成表格之后table的样式并不会根据内容的行数自动扩张

### ISSUE THREAD

**Issue by michellechsy** [sail-sail/ejsExcel#15]
如题，请问这个可以做得到的吗？ 
我在模版里用了“format as table”（如图）， 因为导进去的数据是不确定有多少行的，格式format只弄在了语法那一行，生成的表里也只有第一行保留了表格式。请问填充数据的时候能够自动应用table format吗？是要从代码里设置？或者我的模版里得写些额外的语法（如果要，该怎么写）？
谢谢

![image](https://user-images.githubusercontent.com/7827768/30142904-b68485bc-93b5-11e7-8de8-4d7872748a72.png)

**Comment by sail-sail** [comment]
这个格式不会扩张, 但你可以设置一整张表, table format
选中一整张表, table format

**Comment by michellechsy** [comment]
好的，谢谢
