### ISSUE TITLE
<%%>里可以用javascript的if-else来决定显示value吗

### ISSUE THREAD

**Issue by michellechsy** [sail-sail/ejsExcel#17]
如题，求教～～
 >_<不知道excel里到底能支持啥格式的语法，不熟啊～～～～～

**Comment by sail-sail** [comment]
<%%> 可以支持任意的, 任意的, 任意的 标准的, 标准的, 标准的  javascript语法!!
Excel的格式可以是任意的, 任意的, 任意的, 还不够吗??!!

**Comment by sail-sail** [comment]
Excel宏也可以任意写, 任意写, 所有Excel的特性都支持, VBA, 公式, 图表, 还不够吗???
注意, 任意  任意  任意 任意

**Comment by sail-sail** [comment]
<%
var str = "abc";
if(123 !== 234) str = "cdf";
else str = "bbbbbbbbbbb";
%>
<%=str%>

**Comment by sail-sail** [comment]
<%=true?'aaaa':'bbbb'%>

**Comment by sail-sail** [comment]
javascript的基本语法, 不用我在写了吧? 文档里面有说的很清楚, 支持任意的javascript!!

**Comment by sail-sail** [comment]
<%
var 我定义一个函数 = function(str) {
  return  str+"bbbbb"+"cccc";
}
%>
<%=我定义一个函数("我执行了我定义的函数")%>

**Comment by michellechsy** [comment]
我刚是用了下边这种结构结果出来的数据是空白的，难道不支持从_data_里拿值来判断？
<%
var str = "abc";
if(**rs1.data**) str = "cdf";
else str = "bbbbbbbbbbb";
%>
<%=str%>

**Comment by sail-sail** [comment]
js的基础语法是支持的, 从_data_里面拿也支持
麻烦你自己 用 <% console.log(_data_); %> 打印中间变量去调试好吧?
我不知道你具体的数据格式

**Comment by sail-sail** [comment]
`
<%
var str = "abc";
if(_data_) str = "cdf";
else str = "bbbbbbbbbbb";
%>
<%=str%>
`
具体的javascript的语法, 自己调试好吧? javascript自己没搞对, 就不能说不成熟,

**Comment by sail-sail** [comment]
test/test.xlsx 文档你看了没? 麻烦你先看完, 可以在里面测试

**Comment by michellechsy** [comment]
看过了， 我是在循环data的时候加的条件判断，结果是空。 不过无所谓了，我自己处理完逻辑再传过去，我只是想问问是不是有什么限制而已
![image](https://user-images.githubusercontent.com/7827768/30368615-3d580cd8-98a4-11e7-9809-2946c5ed211b.png)
