### ISSUE TITLE
如何实现嵌套行循环？

### ISSUE THREAD

**Issue by 04swjxy** [sail-sail/ejsExcel#28]
例如:
<% forRow item,i in _data_.orderArr %>     <% forRow goods,j in item.arr %><%= goods.name %>

会报错。正确的怎么写？

**Comment by sail-sail** [comment]
forRBegin可以嵌套循环，但你应该在前面的单元格里面，或者后台，提前嵌套循环构建好新的要循环的数组。显示的时候直接一次循环就可以

**Comment by 04swjxy** [comment]
先谢谢。
不过不好意思，还不是很明白。forRBegin 和forRow 是同一个吗？
你说的后台处理是指我在后台先把嵌套的数组展开，变成不是嵌套的，然后直接一次循环吗？
“在前面的单元格里面”，是什么意思？

**Comment by sail-sail** [comment]
forRBegin 是循环多行, forRow 是循环一行, 例子里面有
后台先把嵌套的数组展开，变成不是嵌套的，然后直接一次循环吗？  -- 对的, 是这样
也可以在前面一点的单元格里面做这个动作, 定义一个新的数组变量, 做这个展开动作, 毕竟 <%%> 里面是可以执行任意的js的

**Comment by 04swjxy** [comment]
哦！明白了，多谢！
还有就是你的这个项目很好，很酷！

**Comment by sail-sail** [comment]
注意 <%%>是可以执行"任意"javascript的, 注意是 任意,  定义内部函数,对象, console.log() 等都是可以的
不客气, 好用就 Star 一下,鼓励下吧
