### ISSUE TITLE
关于循环读取已加载行数据的错误问题

### ISSUE THREAD

**Issue by Kwinin** [sail-sail/ejsExcel#29]
你好!刚开始使用这个ejs导出的时候，效果还是不错的,但是最后还是遇到一个不大不小的问题，就是在循环读取已经打印出来的数据,只读取了模板上的写好的行数据。也就是说如果我有一千多行的数据需要循环导出，模板上就写了三行ejs代码。然后我再次读这张数据的时候，只读取了三行。根据情况，我查找到了问题，在excel表中就已经体现，虽然可以在excel表中可以正常查看数据，但是在你打开该excel表的xml格式文档下，可以发现excel的ref下只有三行数据。也就导致ejsexcel再次读写的时候只有三行数据。在文档中并没有发现你们对row的参数下有相应的处理，所以也是提了个小建议。当然ejsexcel再打印各种复杂的报表是相当便捷好用的，所以也希望ejsexcel能够越来越完善与强大

**Comment by sail-sail** [comment]
?什么问题，你可以test目录下有例子测试

**Comment by sail-sail** [comment]
可以发现excel的ref下只有三行数据. 文档中并没有发现你们对row的参数下有相应的处理
--这两句话不是很理解

**Comment by Kwinin** [comment]
你好!
抱歉打扰了
具体阐述一下我遇到的问题吧
我用ejs模板循环生成一张一千多行的excel表,
但由于业务需要,需再对已生成的表做再次读写,
所以,当我再次读这张表的时候,
发现我一直都只读了三行数据(不是一千多行)
这就是问题所在.
下图是我的模板(只有三行):


下图是原excel表(有一千多行数据)文档:


由此发现ejsexcel循环时,并不是对excel表做一行一行插入,而是在模板上进行读写,由此产生问题,发现文档上没有相关对行的参数进行重置和相关优化
发自网易邮箱大师
在2018年2月1日 09:28，sail-sail<notifications@github.com> 写道：

?什么问题，你可以test目录下有例子测试
