### ISSUE TITLE
/lib64/libc.so.6: version `GLIBC_2.14' not found 报错

### ISSUE THREAD

**Issue by Megic** [sail-sail/ejsExcel#3]
/lib64/libc.so.6: version `GLIBC_2.14' not found (required by /www/pf/Application/class/node_modules/ejsexcel/lib/node-expat/lib/node_expat.node_v50_linux_x64

centos下面报错

**Comment by sail-sail** [comment]
百度搜索 version `GLIBC_2.14' not found
原因是系统的glibc版本太低，软件编译时使用了较高版本的glibc引起的
