### ISSUE TITLE
什么时候ejsExcel能支持xls文件呀？

### ISSUE THREAD

**Issue by combuilder** [sail-sail/ejsExcel#30]
大哥，什么时候ejsExcel能支持xls文件呀？

**Comment by cb288** [comment]
顶起来

**Comment by sail-sail** [comment]
xls格式是二进制格式跟xlsx格式相去胜远, 要想读懂xls格式的文档不容易
但是, 如果你只是想让Excel2003打开xls格式, 那安装个官方Excel插件就可以了
或者你可以找个xlsx格式自动转换成xls格式的工具
我github里面也有用C#做的, xlsx格式转换为xls格式的项目, 也有打印xlsx的服务
