### ISSUE TITLE
能生成折线图么

### ISSUE THREAD

**Issue by HuQiaomu** [sail-sail/ejsExcel#32]
能生成折线图么

**Comment by sail-sail** [comment]
当然可以，只是数据源动态就可以，该怎么样画图表就怎么画
文档上也说了，是任意excel格式，都原样输出，包括VBA，工作表的只读熟悉，是否隐藏等都一样

**Comment by HuQiaomu** [comment]
测试过了, 动态的数据源可以动态改变图表的数据显示, 只是不知道怎么改变图表的列数, 比如柱形图的圆柱数根据数据源的列数来改变
