### ISSUE TITLE
setImmediate is not defined

### ISSUE THREAD

**Issue by xianglong111** [sail-sail/ejsExcel#33]
您好！请问setImmediate is not defined是什么错误？

**Comment by sail-sail** [comment]
setImmediate 是nodejs的内置函数, 请使用高一点版本的nodejs, 才支持setImmediate

**Comment by xianglong111** [comment]
您好，nodejs我已经升级到最新的10.0了还是报这个错误

**Comment by sail-sail** [comment]
不应该啊, setImmediate 是nodejs的全局方法, 是不是哪个地方覆盖了它
试试test目录下面的demo会不会报错?
另外 cmd里面执行 node -v 看看版本
