### ISSUE TITLE
testExcel.js中大小写问题 有可能会误导

### ISSUE THREAD

**Issue by hyphantom** [sail-sail/ejsExcel#34]
作者您好
我在使用中 参考了你的例子
https://github.com/sail-sail/ejsExcel/blob/master/test/testExcel.js

但是const ejsexcel = require("../ejsExcel");可能会误导人
实际我们使用是const ejsexcel = require("ejsexcel");
由于没有注意 于事在windows环境中依然可以使用 
但是在linux中 会找不到lib 花了半小时找问题

**Comment by sail-sail** [comment]
是有这个问题, 谢谢指正
