### ISSUE TITLE
Can I highlight a specific row ( apply specific styling to a row ) 

### ISSUE THREAD

**Issue by POJOa** [sail-sail/ejsExcel#36]
in Chinese : 当前有没有类似的内建功能，可以对输出的某一列的每个单元格定制样式，例如，将字体标红？

**Comment by sail-sail** [comment]
制作模板的时候, 就可以对一整列或者一整行进行单元格格式, 字体等设置
对于动态格式, 可以使用Excel自带的 动态单元格格式
实在不行, 还可以使用 VBA

**Comment by POJOa** [comment]
我这边的需求是每个月输出的某个统计值和上个月的数值比较，如果有变动，就要把该列标红，而且上月的数值是不输出到表的，这样应该都不行。可能我会去看看源码，不知道有没有调整格式的方法，谢谢了。

**Comment by sail-sail** [comment]
可以把上月的数值放在隐藏的工作表里面, 然后再用VBA去判断,去比较, 或者 "条件格式"

**Comment by POJOa** [comment]
好的 我研究一下 谢谢了
