### ISSUE TITLE
null 字段 渲染空白字段，而不是NULL

### ISSUE THREAD

**Issue by JaylanChen** [sail-sail/ejsExcel#39]
希望null字段渲染Excel时为空白字段“”，而不是“NULL”。

https://github.com/sail-sail/ejsExcel/blob/master/ejsExcel.js#L228

str = "NULL";  →  str = "";

**Comment by sail-sail** [comment]
好, 有道理

**Comment by michellechsy** [comment]
请问这个bug没修吗？ 我现在导excel还能看到null

**Comment by sail-sail** [comment]
发布了, 3.5.4 版本

**Comment by michellechsy** [comment]
好的，谢谢大佬～～
