### ISSUE TITLE
循环数据的时候是否可以指定作用范围是某几个column？

### ISSUE THREAD

**Issue by michellechsy** [sail-sail/ejsExcel#45]
use case是这样的，我们想要弄一个模版是B：F循环显示一批数据， H：J循环显示另一批数据。 可以做到吗？

**Comment by sail-sail** [comment]
不可以哦, 处理方法一般是提前构建好需要循环的数据, 然后一次性循环渲染出来
或者, 做一个隐藏的sheet, 然后用Excel公式或VBA在需要显示数据的地方引入过来数据
