### ISSUE TITLE
支持动态列名么

### ISSUE THREAD

**Issue by wulucxy** [sail-sail/ejsExcel#46]
@sail-sail 项目中实际需求是列名是根据数据动态生成的，目前是否支持，如果有，是否有demo？

感谢支持

**Comment by sail-sail** [comment]
有, 也有例子
test/test.bat 直接可以测试, 看看里面的内容 test/test.xlsx 是完整的例子, 也是完整的文档, 要看完, 也可以当场测试

**Comment by wulucxy** [comment]
mac 下如何执行bat文件

**Comment by sail-sail** [comment]
那你就看一下里面的内容, 就一行 node ./testExcel.js
