### ISSUE TITLE
同一单元格里变量和字符串共存问题

### ISSUE THREAD

**Issue by DuJiming** [sail-sail/ejsExcel#50]
我在一个单元格里设置了
```
<%~_data_[0].year%><%="年"%>
```
像这样
![image](https://user-images.githubusercontent.com/36750680/55865927-e6bd1080-5bb1-11e9-8a0d-e1cf7bd5b7ea.png)

data：
```
const data = [{year: 2019, month: 4}, {name: '小明'}];
```
然后打印出来变成了这样
![image](https://user-images.githubusercontent.com/36750680/55866051-2683f800-5bb2-11e9-8bec-6e19f593ba3a.png)
是我哪里写错了么
mac下
node8.12.0

**Comment by sail-sail** [comment]
同一个单元格只能有一个输出符号, 你这种, 明显只能是字符型的单元格, 应该用<%= 才对, 应该改成这样:
`<%=_data_[0].year + "年"%>`

**Comment by sail-sail** [comment]
注意, Excel模板做好之后, 要在 微软的Excel 上打开, 并且保存一下, 因为ejsExcel只完美支持, 微软Excel的格式

**Comment by DuJiming** [comment]
好的，明白了，感谢
