### ISSUE TITLE
failed to renderExcel with buf data: Cannot read property 'cfile' of undefined

### ISSUE THREAD

**Issue by michellechsy** [sail-sail/ejsExcel#51]
Help~~~

Debug: internal, implementation, error 
    TypeError: Cannot read property 'cfile' of undefined
    at Proxy.<anonymous> (/Users/..../node_modules/ejsexcel/ejsExcel.js:680:57)
    at Generator.next (<anonymous>)
    at step (/Users/..../node_modules/ejsexcel/ejsExcel.js:1:191)

**Comment by sail-sail** [comment]
You have to use Microsoft Office Excel 2007 version or more to make templates

**Comment by sail-sail** [comment]
test/test.xlsx   is  the demo

**Comment by gonlex** [comment]
i have the same error and im using .xlsx

**Comment by sail-sail** [comment]
It may be no a effective .xlsx file
