### ISSUE TITLE
renderExcel 方法返回类型与定义不一致，版本3.5.4

### ISSUE THREAD

**Issue by 200688523** [sail-sail/ejsExcel#52]
定义中返回Buffer
export declare function renderExcel(exlBuf: Buffer, _data_: any): Buffer;

而实际返回的是Promise 对象。

导致会报以下错误：
(node:338628) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token ;
    at Object.<anonymous> (excel_test\node_modules\ejsexcel\ejsExcel.js:1133:26)
    at Generator.next (<anonymous>)
    at step (excel_test\node_modules\ejsexcel\ejsExcel.js:1:129)
    at excel_test\node_modules\ejsexcel\ejsExcel.js:1:306
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:338628) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:338628) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by sail-sail** [comment]
3.5.5版本, 已解决

**Comment by 200688523** [comment]
> 3.5.5版本, 已解决

好的，辛苦了。
