### ISSUE TITLE
请问，如何基于数据动态生成工作表

### ISSUE THREAD

**Issue by 200688523** [sail-sail/ejsExcel#53]
请问，如何基于数据动态生成工作表

**Comment by sail-sail** [comment]
工作表 不能动态生成了, 但是可以利用VBA去切割工作表, 隐藏的工作表给VBA提供数据

**Comment by 200688523** [comment]
> 工作表 不能动态生成了, 但是可以利用VBA去切割工作表, 隐藏的工作表给VBA提供数据

嗯，谢谢
