### ISSUE TITLE
可以只指某一个Sheet进行渲染吗？

### ISSUE THREAD

**Issue by JasonWuuu** [sail-sail/ejsExcel#54]
我有这样一个需要：设置Sheet1中单元格A1 为<%=__data__.value1%>, 渲染出来的结果为1， 另一个Sheet2中的单元格A2为=Sheet1!A1, 实际上它是一个链接指向了Sheet1中单元格A1，结果也为1，但结果渲染出来的就是数字1，而不是=Sheet1!A1这个链接推算出来的1，我希望这个结果是由=Sheet1!A1这个链接推算出来，有什么办法吗？

**Comment by sail-sail** [comment]
=Sheet1!A1 是公式, 例子里面有专门的动态公式说明, <%# 输出动态公式
<%#"=Sheet1!A1"%>

**Comment by JasonWuuu** [comment]
牛拜
