### ISSUE TITLE
某一列想做成下拉列表怎么处理

### ISSUE THREAD

**Issue by yoder** [sail-sail/ejsExcel#56]
某一列想做成下拉列表怎么处理

**Comment by sail-sail** [comment]
在模板里面, 选中这一整列, 给这一整列设置下拉就可以了
如果做下拉, 百度搜索  Excel怎么设置下拉菜单-百度经验

**Comment by yoder** [comment]
> 在模板里面, 选中这一整列, 给这一整列设置下拉就可以了
> 如果做下拉, 百度搜索 Excel怎么设置下拉菜单-百度经验

感谢回答，看了下demo的模板，已经想到了
