### ISSUE TITLE
Error opening department cell data after exporting excel

### ISSUE THREAD

**Issue by MANJUSAK** [sail-sail/ejsExcel#57]
template
[template.xlsx](https://github.com/sail-sail/ejsExcel/files/3829705/template.xlsx)
data
const data = [{ name: '刘桂娟', mustIssue: 6000, realIssue: 4000, date: 'test', project: 'test', team: 'test', total: 'test', personType: 'test', bankAcc: 'test', bankName: 'test' }]

error
![1573446610](https://user-images.githubusercontent.com/21168513/68561130-2f59e680-047f-11ea-9a04-64de778109b1.jpg)

Some content in Excel has a problem, let us try to recover, if you trust the source of this workbook, click Yes.

**Comment by MANJUSAK** [comment]
Some content in Excel has a problem, let us try to recover, if you trust the source of this workbook, click Yes.

**Comment by sail-sail** [comment]
这样写是错的:
```发放表（<%=_data_[0].dateTime%>）```

一旦某个单元格有 <%%>, 就必须改写成这样:
```<%="发放表（"+_data_[0].dateTime+"）"%>```
或者这样:
```<%=`发放表（${_data_[0].dateTime}）`%>```
或者这样:
```<%="发放表（"%><%=_data_[0].dateTime%><%="）"%>```

**Comment by MANJUSAK** [comment]
I understand, I understand, thank you very much.

**Comment by MANJUSAK** [comment]
solved
