### ISSUE TITLE
如何让单元格内容换行

### ISSUE THREAD

**Issue by liu-minjie** [sail-sail/ejsExcel#59]
我在内容里加了 \r\n, 生成的excel打开时显示没有换行, 双击单元格后才会换

**Comment by sail-sail** [comment]
明天我自己测试一下看看

**Comment by liu-minjie** [comment]
> 明天我自己测试一下看看

https://github.com/protobi/js-xlsx/issues/73#issuecomment-308316352
可以看一下这个回复

**Comment by oubaguilai** [comment]
![image](https://user-images.githubusercontent.com/24708305/91785930-04709700-ec39-11ea-8bb4-f9b6bbf226a2.png)
我也遇到这个问题了，我是通过设置alignment.wrapText为true解决这个问题的。
insert \r\n in cell value. line breaking only work when alignment.wrapText is true.
