### ISSUE TITLE
如何渲染动态图？

### ISSUE THREAD

**Issue by Yuanr6039** [sail-sail/ejsExcel#60]
这个能动态渲染图片吗

**Comment by sail-sail** [comment]
能啊, test/test.xlsx里面有例子, <%_img_(JSON对象)

**Comment by Yuanr6039** [comment]
> 能啊, test/test.xlsx里面有例子, `<%_img_(JSON对象)`

感谢大佬

**Comment by Yuanr6039** [comment]
> 能啊, test/test.xlsx里面有例子, `<%_img_(JSON对象)`
大佬 能实现n个sheet模版 根据数据集动态生成m个sheet吗

**Comment by Yuanr6039** [comment]
@sail-sail 
大佬 能实现n个sheet模版 根据数据集动态生成m个sheet吗

**Comment by sail-sail** [comment]
暂不直接支持哦, 但支持动态删除sheet, 动态隐藏sheet
也可以生成一个sheet, 然后用VBA去切割成多个sheet

**Comment by Yuanr6039** [comment]
@sail-sail 
额 好吧 我再看看 谢谢 大佬

**Comment by Yuanr6039** [comment]
大佬 我太菜了 怎么显示不了呢

**Comment by sail-sail** [comment]
测试例子, 例子是能显示的, 仔细对比例子, 测试例子,
并且模板要至少提前插入一张图片, 可以是一像素的透明图片

**Comment by Yuanr6039** [comment]
知道了， 只支持相对的， 绝对路径（线上的不支持）

**Comment by sail-sail** [comment]
你可以把图片下载成buffer对象, 直接传入buffer对象进去, 也可以

**Comment by Yuanr6039** [comment]
好的 打扰了 大佬
