### ISSUE TITLE
一个单元格放入多张图片

### ISSUE THREAD

**Issue by GuiLingWN** [sail-sail/ejsExcel#61]
请教下一个单元格放入多张图片怎么操作，
另外图片有宽高属性参数么，目前好像是充满整个单元格的

**Comment by sail-sail** [comment]
似的, 目前基本只能让图片充满多少个单元格, 当然也可以控制图片宽高填满多少个单元格,
具体对图片更细节的控制, 你应该可以尝试用VBA来做到

**Comment by sail-sail** [comment]
似的, 目前基本只能让图片充满多少个单元格, 当然也可以控制图片宽高填满多少个单元格,
具体对图片更细节的控制, 你应该可以尝试用VBA来做到

**Comment by GuiLingWN** [comment]
图片有宽高属性参数么，具体参数是什么，我看了_img_部分源码好像没有相关参数

**Comment by sail-sail** [comment]
图片有宽高属性参数没看懂Excel是什么个宽高规律, 所以我没给, 只看懂了图片占用多少个单元格的参数
你可以通过调整单元格来控制图片, 实在想用精细的图片操作, 可以用 VBA, 可以在模板里面直接写VBA代码

**Comment by GuiLingWN** [comment]
了解了，多谢
