### ISSUE TITLE
<%#动态公式，不生效，总是为0，编辑回车后才显示正确的值

### ISSUE THREAD

**Issue by kongku** [sail-sail/ejsExcel#66]
例如<%#"=C"+_row+"+E"+_row%>，设置两个单元格相加，导出的Excel值为0，只有点击单元格编辑回车后，才会显示正确的值？这个如何解决？

**Comment by kongku** [comment]
大家没有这个问题吗？是因为我用wps打开的原因？

**Comment by wy2022** [comment]
我也遇到一样的问题

**Comment by wy2022** [comment]
你解决了吗，兄弟

**Comment by sail-sail** [comment]
因为动态公式不支持WPS, 你WPS编辑好模板之后, 用微软Office Excel打开, 点击一下保存按钮, 然后以此作为模板就可以了
