### ISSUE TITLE
可否支持 1997-2003 版本的excel呢？

### ISSUE THREAD

**Issue by liuxingpluck** [sail-sail/ejsExcel#67]
可否支持 1997-2003 版本的excel呢？
因为 我们这面向的客户 使用的交互格式为 xls 格式，且带有 颜色背景之类的，我们也想换成 07 xlsx版本，但是他们不同意

问问这边，您能不能加个支持呢？

**Comment by sail-sail** [comment]
不用换啊! 让他们给Excel2003装个Excel2007的插件就可以了直接打开Excel2007以上的版本了, 微软官方有补丁, 你搜索一下 "Excel2003补丁"
