### ISSUE TITLE
数据量再30万行该如何渲染到excel模板里面

### ISSUE THREAD

**Issue by ysfdwind** [sail-sail/ejsExcel#68]
data 数据量可能超过30万行，数量列预计30列，再使用 ejsexcel.renderExcel(exlBuf, data).then((exlBuf2) => {} 太慢了，能用流输入了，边读边输入

**Comment by sail-sail** [comment]
可以将nodejs启动参数设置内存大一点, 设置成4G等
然后, 如果要导出非常大的数据量, 然后又是简单的列表格式, 最好用CSV格式, 可以用流的方式导出
然后给CSV格式的后缀改成.csv或者.xlsx格式, 任然可以用Excel打开
