### ISSUE TITLE
能否在excel中插入一张在线图片

### ISSUE THREAD

**Issue by jaimorlin** [sail-sail/ejsExcel#71]
我想在导出来的时候，有一列是展示在线图片，支持吗？

**Comment by sail-sail** [comment]
只是图片啊, 但是你需要先用nodejs的类库比如request, axios的下载图片到内存, 或者本地, 然后再用ejsExcel的API模板里面插入图片
<%__img()%>, 具体文档里面有例子, 有注意事项说明, 现成例子测试

**Comment by jaimorlin** [comment]
能否具体一点，测试例子在哪个位置，我就是没有找到才提的issue @sail-sail     ~_~

**Comment by sail-sail** [comment]
test目录下, 双击test.bat就是测试例子了 , 然后具体的模板是 test.xlsx, 你可以修改里面的内容, 然后重新执行 test.bat 就知道效果了
然后test.xlsx本身也是文档, 要看完里面的所有说明, 里面也有如何展示动态图片的说明
[https://ejsexcel.com/ejs1.jpg](url)

**Comment by jaimorlin** [comment]
好的，非常感谢，非常感谢！！！已解决。这个项目很好，希望大佬持续更新维护。一个大大的牛逼送给你。支持！！

<%_img_({imgPh:"图片绝对位置",cNvPrName:"图片名称(可不填)",cNvPrDescr:"图片描述(可不填)",cellNumAdd:2,rowNumAdd:2})%>    就好了

**Comment by sail-sail** [comment]
注意一下啊, imgPh 可以是图片路径,也可以是一个Buffer对象, 如果你从网络上下载的图片不是很大,  就可以不经过硬盘, 直接下载成Buffer对象, 传递给imgPh,  都可以哈

**Comment by jaimorlin** [comment]
那问个问题，什么样的算大？假如我有一个列表，总共20张图片，一张大概800kb，这样算大吗？

**Comment by sail-sail** [comment]
模板本身不可能有那么多图片吧, 导出来之后才是有那么多图片吧? 导出来之后的大小无所谓, 实在不行, 启动nodejs的时候, 扩大内存就可以
模板本身会怕过大, 但图片的大小是无所谓的, 后来我加入了编译ejsExcel的缓存技术, 大, 就没那么怕了
你看看参数, 有个缓存参数需要设置

**Comment by jaimorlin** [comment]
对了，再询问一下，插入表格的图片可以设置大小吗？比如设置为单元格的85%宽度，75%高度
