### ISSUE TITLE
forRow嵌套在forRBegin里面，会发生错乱

### ISSUE THREAD

**Issue by kongku** [sail-sail/ejsExcel#75]
当forRow嵌套在forRBegin里面使用，同时forRow下一行就使用forREnd，那么，生成的表格中，forRBegin循环的第一行没有循环生成并发生错位，在forRow循环生成的行间会插入一个空行，如下图：
![0](https://user-images.githubusercontent.com/29189288/230544093-8e5c3481-8fd1-4a9b-b41d-672af7a5164b.png)
![1](https://user-images.githubusercontent.com/29189288/230544114-e97db862-834d-46b5-81ad-b6f9a970446b.png)
只要在forRow与forREnd之间插入一行，问题就能解决，如下图。
![2](https://user-images.githubusercontent.com/29189288/230544543-91d33176-4b6d-4fc6-8105-bcb32fd69ee8.png)
![3](https://user-images.githubusercontent.com/29189288/230544546-4a378a37-34cf-4716-a915-36743f36da7f.png)
对于forRBegin嵌套在forRBegin使用，也有类似的情况，两个循环的forREnd不能在同一行。

**Comment by sail-sail** [comment]
`<%forRBegin%><%forRow%>` `forRow`直接放在`forRBegin`后面, 紧贴着, 别换行
你换行了, 就意味着你想要中间出现空白行

**Comment by kongku** [comment]
> `<%forRBegin%><%forRow%>` `forRow`直接放在`forRBegin`后面, 紧贴着, 别换行 你换行了, 就意味着你想要中间出现空白行

好的，那只能去修改数据结构，让第一行的数据也放到forRow的数据中。
