### ISSUE TITLE
如果ifCBegin的条件为false，那么ifCBegin与ifCEnd之间的单元格会被删掉，导致右边的单元格向左偏移

### ISSUE THREAD

**Issue by kongku** [sail-sail/ejsExcel#77]
原本想使用ifCBegin控制单元格在某个条件下才填写数据，其他情况下为空，却发现条件为假的时候，单元格并不是简单的为空，而是单元格被删除，就像在excel中删除一个单元格，然后选择右侧单元格左移的情况。请问，能否增加类似于if-else的逻辑关系吗？
![demo](https://github.com/sail-sail/ejsExcel/assets/29189288/09f3b4bb-a4dd-4095-bcb6-0068b1031364)

**Comment by sail-sail** [comment]
你直接这样就可以了```<#=a ? a : ""#>```
或者```<# var a = "bbb"; if (!a) { a = "" } #><#=a#>```
你懂的, 本质上就是JavaScript的语法, 任意JavaScript都可以,  任意, 任意

**Comment by kongku** [comment]
> 你直接这样就可以了`<%=a ? a : ""%>` 或者`<% var a = "bbb"; if (!a) { a = "" } %><%=a%>` 你懂的, 本质上就是JavaScript的语法, 任意JavaScript都可以, 任意, 任意

明白，谢谢。
