### ISSUE TITLE
如何添加网络图片

### ISSUE THREAD

**Issue by luziqwe** [sail-sail/ejsExcel#79]
项目有个需求就是导出的EXCEL里面会需要有图片,但是_img_()方法无法渲染出来,跨域我也处理了,但是就是图片出不来

**Comment by sail-sail** [comment]
渲染图片, 只能是本地图片, 或者是buffer对象传递给 imgPh 参数, demo里面的例子是没问题的, 并且模板里面必须提前有一张图片, 1像素的透明图片也可以
你可以用 fetch 或者 request 先下载图片到本地为临时文件, 或者buffer对象再传递进去
