### ISSUE TITLE
请教一个问题，循环一个数组，如果数组为空则输出一个空行怎么处理？

### ISSUE THREAD

**Issue by shuperry** [sail-sail/ejsExcel#9]

**Comment by shuperry** [comment]
忘了这碴了，直接在数据源源头处理，判断数组为空时自己往里面加一条空的记录

**Comment by sail-sail** [comment]
对的, 非常正确, 直接在数据源源头处理 好所有需要显示的数据, ejsExcel最好只负责显示

**Comment by shuperry** [comment]
@sail-sail 要是能在功能里加上 if else 配套的标签判断功能就更简单了
